// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace PlayCade.iOS
{
	public partial class MainViewController : UIViewController
	{
		public MainViewController(IntPtr handle) : base(handle)
		{
		}
	}
}
